### ISSUE TITLE
Probably not an Issue but something i would to to do 

### ISSUE THREAD

**Issue by 0katz** [nbwar/NWCalendarView#2]
Where do i remove the red line that appears when i click on a date? I want to select a date and highlight that date specifically not the entire week and add an event on the date selected. I hope you can help fix this minor solution thanks in advance.

**Comment by nbwar** [comment]
In order to select just one date set `calendarView.selectionRangeLength = 1`. And what do you mean by add an event on the date selected?

**Comment by 0katz** [comment]
thank you for the fast reply! I mean an EKEventStore() Let's say i select July 31 and i want to write a "note" on that day and save it.  I can probably go on from here but thanks anyways! but if you know an efficient way of doing this please i would love to learn it.

```
  var event:EKEvent = EKEvent(eventStore: eventStore) 

    event.title = "Test Title" 
    event.startDate = NSDate() 
    event.endDate = NSDate() 
    event.notes = "This is a note" 
    event.calendar = eventStore.defaultCalendarForNewEvents 
```
