### ISSUE TITLE
the wrong day 

### ISSUE THREAD

**Issue by marcandree** [nbwar/NWCalendarView#7]
Hello, 
I downloaded your calendar which is simple and perfect , but there is a problem with the day . 
For example the 1st of January 2016 is a Friday not a Thursday , there is always the wrong day on the calendar .

Thanks  in advance for your respond

**Comment by nbwar** [comment]
I'm not seeing this issue. Maybe its a timezone issue what timezone are you in?

**Comment by marcandree** [comment]
Hi Thanks for your respond , Iam in Swizterland
GMT+1

**Comment by nbwar** [comment]
Changed my timezone to Switzerland, Still showing up correct for me.
<img width="342" alt="screen shot 2015-12-01 at 5 20 40 pm" src="https://cloud.githubusercontent.com/assets/1980594/11506449/73f46dce-9804-11e5-9257-0372f0f5c6f0.png">

**Comment by marcandree** [comment]
![img_6211](https://cloud.githubusercontent.com/assets/6263692/11510182/b1a60548-9862-11e5-9b9c-b67eff0657a4.jpg)
This is the screen I got and the code : 

```
   calendarView.layer.borderWidth = 1
    calendarView.layer.borderColor = UIColor.lightGrayColor().CGColor
    calendarView.backgroundColor = UIColor.whiteColor()
    let newDate3 = date
    calendarView.selectedDates = [newDate3]
   calendarView.selectionRangeLength = 1
    calendarView.maxMonths = 4
    calendarView.delegate = self
    calendarView.createCalendar()
    calendarView.scrollToDate(newDate3, animated: true)
```

**Comment by nbwar** [comment]
What are your Region formats in Settings on your device? I've tried changing timezone, calendar type, and everything else but I am unable to reproduce this bug.

**Comment by marcandree** [comment]
![img_6214](https://cloud.githubusercontent.com/assets/6263692/11512509/ba62e29e-986e-11e5-8c29-f069107f1609.jpg)

This is my setting

**Comment by nbwar** [comment]
That did it, Setting region to Switzerland is what brakes it. I believe its because day of week starts on  Sunday as opposed to Monday. I'll see if i can do a quick fix for you now.

**Comment by marcandree** [comment]
Thanks a lot :+1:
